id = "supergreatmonokai"
name = "SuperGreatMonokai"
version = "0.0.1"
schema_version = 1
authors = ["SuperGregM"]
description = "Great Zed theme based off sublime text's monokai mixed with VSCode's monokai."
repository = "https://github.com/SuperGregM/SuperGreatMonokai-Zed"
